#ifndef HEADER_H_SRC_VERSIONS     // equivalently, #if !defined HEADER_H_
#define HEADER_H_SRC_VERSIONS

#include <string>
// These variables are autogenerated and compiled
// into the library by the version.cmake script
extern "C"
{
    extern const char* GIT_TAG;
    extern const char* GIT_REV;
    extern const char* GIT_BRANCH;
    extern int GIT_INT_VER;
}

const char* git_version(void)
{
    return GIT_TAG;
}

/*
const char* ph_git_revision(void)
{
    return GIT_REV;
}*/

std::string git_revision(void)
{
    return std::string(GIT_REV);
}

const char* git_branch(void)
{
    return GIT_BRANCH;
}

uint16_t git_version_int16(){
    return static_cast<uint16_t>(GIT_INT_VER/1000);
}


uint32_t git_version_int(){
    return GIT_INT_VER;
}


#endif